name: CI/CD CA workflow
on:
    push:
        branches:
            - 'v[0-9]*\.[0-9]*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code for workflow1
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner in repo mode
              id: trivy_code_scan
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'trivy-results.txt'
                severity: 'CRITICAL'
                exit-code: 1
            
            - name: Slack Notification when Code Scan Fails
              uses: rtCamp/action-slack-notify@v2
              if: always() && steps.trivy_code_scan.outcome=='failure'
              env:  
                SLACK_WEBHOOK: ${{ secrets.SUBMISSION_WEBHOOK }}
                SLACK_MESSAGE: 'Failed trivy scan, see report for details.'

            - name: Upload to slack step
              uses: adrey/slack-file-upload-action@master
              if: always() && steps.trivy_code_scan.outcome=='failure'
              with:
                token: ${{ secrets.TOKEN }}
                path: trivy-results.txt
                channel: submission

            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.1.1
              with:
                cosign-release: 'v2.2.0'

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: inella/cicd:${{ github.sha }}
    
            - name: Sign image with a key
              run: |
                cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
              env:
                TAGS: "inella/cicd"
                COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
                DIGEST: ${{ steps.build-and-push.outputs.digest }}
        

            - name: Slack Notification when Code Scan Succeeds
              uses: rtCamp/action-slack-notify@v2
              env:  
                SLACK_WEBHOOK: ${{ secrets.SUBMISSION_WEBHOOK }}
                SLACK_MESSAGE: "*Name*: Tong Chang\n *MatriculationNumber*: A0285978Y\n *Email*: e1221790@u.nus.edu\n *Repository*: ${{ github.server_url }}/${{ github.repository }}\n *DockerHubURL*: https://hub.docker.com/repository/docker/inella/cicd"
            